### ISSUE TITLE
New menu selector temporarily locks randomly-unlocked tiles

### ISSUE THREAD

**Issue by GitGeddes** [GitGeddes/ChunkPicker#1]
If a tile was randomly picked through the Chunk Unlocker, then the Chunk Info selector will change it visually into a "locked" tile rather than an "unlocked" tile. However, switching back to the Chunk Unlocker menu will return the red borders.

To reproduce:
* Open Chunk Unlocker menu
* Mark any tile as "potential"
* Click the "Pick a potential random chunk!" button
* Wait for the animation to finish, then switch to the Chunk Info menu
* Select the newly-unlocked tile, then select any other tile

Doing all of this doesn't return the newly-unlocked tile to the "unlocked" type. Instead, it changes the tile to the "locked" status. However, if the user changes back to the Chunk Unlocker menu, then the newly-unlocked tile returns. The same issue happens with the menu set to "Menu" as it does when set to "Chunk Info."

**Comment by Jeaper** [comment]
It was due to chunks from the random chunk selection adding the chunks as a string instead of a number. should now be safeguarded.
https://github.com/GitGeddes/ChunkPicker/commit/d6876e864b328100231307d83065aa70dc9d6b45
