### ISSUE TITLE
Import not working properly

### ISSUE THREAD

**Issue by akuinu** [GitGeddes/ChunkPicker#2]
If you import the exported file it will not result same board - flipped axis.
 
To reproduce:

- Open Chunk Unlocker menu
- Mark chunks that are not on diagonal
- Open Import/Export menu
- Export the info to fail
- Reload the page
- Open Import/Export menu
- Import previously exported file

**Comment by Jeaper** [comment]
'getSpriteIndexFromPosition()'  used a x and y flipped.
Fixed as of https://github.com/GitGeddes/ChunkPicker/commit/7d9a7b023d35a939e16d37ebe7dcfbc8c0d2edee
